use_frameworks!

target 'GGNLocationPicker_Example' do
  pod 'GGNLocationPicker', :path => '../'

  target 'GGNLocationPicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
